### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by Horikumi** [EchterAlsFake/xvideos_api#1]
Pages doesn't work correctly even if I do pages=1 or pages=3
It sends same content 
Even for famous search i mean.

**Comment by EchterAlsFake** [comment]
Hi, I just tested it and I don't have these issues. For me it returned different content.

Maybe there's an issue with the old version, since I updated a lot the last days but didn't push to Pypi yet.


could you do this real quick:

```
pip uninstall xvideos_api
pip install git+https://github.com/EchterAlsFake/xvideos_api
```

If the error persists, I'd need to see your code you are using.

Thanks :)

**Comment by EchterAlsFake** [comment]
Yes, it would be very good to see your results too. Thanks
