### ISSUE TITLE
how to get directlink mp4 url from xvideos

### ISSUE THREAD

**Issue by joesandiroz2** [EchterAlsFake/xvideos_api#11]
i want get directlink mp4 without token or whatever . because i will use remote upload to my video hosting .

where i get
```

from xvideos_api import Client, Quality, threaded, default, FFMPEG
# Initialize a Client object
client = Client()

# Fetch a video
url = "https://www.xvideos.com/video.heohkfkfb68/38481963/0/young_show_off_sluts_waiting_for_someone_to_fuck_vol._19"

video_object = client.get_video(url)
print(dir(video_object))
print(video_object.m3u8_base_url)
```

**Comment by EchterAlsFake** [comment]
Hi, I can not do that, because videos on xvideos are split into smaller segments. This process makes HLS streaming possible which allows for a variable bitrate on different quality settings. There are sites like `eporner` or `hqporner` which store the raw video file which you can directly download and upload to your platform, but segments need to be processed seperately. 

I also don't want that my APIs are used for mass-distributing content to other platforms!
